name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Rendre gradlew exécutable
        working-directory: KAJY_Android_V5_1_1
        run: chmod +x gradlew

      - name: Build APK Debug
        working-directory: KAJY_Android_V5_1_1
        run: ./gradlew assembleDebug

      - name: Télécharger l'APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: KAJY_Android_V5_1_1/app/build/outputs/apk/debug/app-debug.apk
